name: Linux RDP via Tailscale

on:
  workflow_dispatch:

jobs:
  rdp-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install desktop + XRDP
        run: |
          sudo apt update -y
          sudo apt install -y xfce4 xfce4-goodies xrdp dbus-x11
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

          # Create RDP user
          sudo adduser rdpuser --disabled-password --gecos ""
          echo "rdpuser:avishidk" | sudo chpasswd

          # Configure session for XFCE (run as root to avoid permission issues)
          echo xfce4-session | sudo tee /home/rdpuser/.xsession > /dev/null
          sudo chown rdpuser:rdpuser /home/rdpuser/.xsession
          sudo chmod 644 /home/rdpuser/.xsession

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-linux-${{ github.run_id }}

          # Get Tailscale IP
          TS_IP=$(tailscale ip -4 | head -n 1)
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV
          echo "Tailscale IP: $TS_IP"

      - name: Verify XRDP is listening
        run: |
          sudo ss -tulpn | grep 3389 || echo "⚠️ XRDP not listening on port 3389"

      - name: Show connection details
        run: |
          echo ""
          echo "======================================"
          echo "✅ RDP Access via Tailscale is Ready!"
          echo "--------------------------------------"
          echo "Tailscale IP: $TAILSCALE_IP"
          echo "Username: rdpuser"
          echo "Password: avishidk"
          echo "--------------------------------------"
          echo "Connect with any RDP client:"
          echo "  mstsc /v:$TAILSCALE_IP"
          echo "Session type: Xorg"
          echo "======================================"
          echo ""

      - name: Keep RDP session alive
        run: |
          echo "Keeping RDP session alive..."
          while true; do
            echo "$(date): runner active"
            sleep 300
          done
