name: Linux RDP via Tailscale (Stable)

on:
  workflow_dispatch:

jobs:
  rdp-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install full XFCE desktop + XRDP (stable config)
        run: |
          sudo apt update -y
          sudo DEBIAN_FRONTEND=noninteractive apt install -y \
            xfce4 xfce4-goodies xorg xrdp dbus-x11 x11-xserver-utils policykit-1 \
            pulseaudio

          # Enable and start XRDP
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

          # Create RDP user
          sudo adduser rdpuser --disabled-password --gecos ""
          echo "rdpuser:avishidk" | sudo chpasswd

          # Create runtime directory for dbus
          USER_ID=$(id -u rdpuser)
          sudo mkdir -p /run/user/$USER_ID
          sudo chown rdpuser:rdpuser /run/user/$USER_ID
          sudo chmod 700 /run/user/$USER_ID

          # Create home environment
          sudo mkdir -p /home/rdpuser/.config
          echo "exec dbus-launch --exit-with-session startxfce4" | sudo tee /home/rdpuser/.xsession > /dev/null
          echo "export XDG_RUNTIME_DIR=/run/user/$USER_ID" | sudo tee -a /home/rdpuser/.profile > /dev/null
          echo "export XDG_CONFIG_DIRS=/etc/xdg" | sudo tee -a /home/rdpuser/.profile > /dev/null
          echo "export DISPLAY=:10" | sudo tee -a /home/rdpuser/.profile > /dev/null
          sudo chown -R rdpuser:rdpuser /home/rdpuser
          sudo chmod 644 /home/rdpuser/.xsession

          # Restart XRDP after environment setup
          sudo systemctl restart xrdp

          # Sanity check
          echo "✅ XFCE + XRDP installed successfully."

      - name: Install Tailscale and connect
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} \
                            --hostname=gh-linux-${{ github.run_id }} \
                            --accept-routes --accept-dns=true
          TS_IP=$(tailscale ip -4 | head -n 1)
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV
          echo "✅ Tailscale connected with IP: $TS_IP"

      - name: Verify XRDP service
        run: |
          echo "Checking XRDP status..."
          sudo systemctl status xrdp | head -n 15
          echo ""
          sudo ss -tulpn | grep 3389 && echo "✅ XRDP is listening on port 3389"

      - name: Display RDP connection details
        run: |
          echo ""
          echo "======================================"
          echo "✅ LINUX RDP VIA TAILSCALE IS READY"
          echo "--------------------------------------"
          echo "Tailscale IP : $TAILSCALE_IP"
          echo "Username     : rdpuser"
          echo "Password     : avishidk"
          echo "Session type : Xorg"
          echo "--------------------------------------"
          echo "👉 Connect using any RDP client:"
          echo "    mstsc /v:$TAILSCALE_IP"
          echo "======================================"
          echo ""

      - name: Keep session alive
        run: |
          echo "Keeping RDP session alive for 6 hours..."
          while true; do
            echo "$(date): RDP session active"
            sleep 300
          done
